CC=gcc
CFLAGS:= 
LDFLAGS:=

OBJS=$(SRCS:.c=.o)

OUTDIR=../../build

all : $(EXE)
	$(info make $@ for $(EXE)...)

$(EXE) : $(OBJS)
	@$(CC) $^ $(LDFLAGS) -o $@

%.o : %.c $(DEPS)
	@$(CC) $(CFLAGS) -c $<

clean:
	$(info make $@ for $(EXE)...)
	@rm -f $(OBJS)

clobber:
	$(info make $@ for $(EXE)...)
	@rm -f $(OBJS) $(EXE)

install:
	$(info make $@ for $(EXE)...)
	@cp $(EXE) $(OUTDIR)

uninstall:
	$(info make $@ for $(EXE)...)
	@rm -f $(OUTDIR)/$(EXE)
